package-lock.json
package.json

Agregar librería ngx-infinite-scroll
1. Se instala paquete ngx-infinite-scroll

fix(module): agrega libreria ngx-infinite-scroll

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/login/components/login/login.html
src/app/login/login-routing.module.ts
src/app/login/routing-guard.ts
src/app/monitor-activaciones/monitoreo-activaciones.component.html
src/index.html

Arreglar error en consola al seleccionar un paciente en activaciones
1. Se reemplazó resultadoMensajes.length por resultadoMensajes?.length en el front de activaciones
2. Se fusionaron las columnas de teléfono/email, y se agregó un icono para distinguir si el dato corresponde a un móvil o a un correo

MONITOREO: arreglo de error en activaciones

---

src/app/monitor-activaciones/monitoreo-activaciones.component.html

Visualizar en la lista de mensajes el código enviado en cada mensaje de activación
1. Agrega una columna en la lista de mensajes del sidebar 
2. 
3.

Agrega el código enviado al paciente para activación de app

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/buscador-snomed/buscador-snomed.component.html
src/app/buscador-snomed/buscador-snomed.component.ts
src/styles.scss

https://proyectos.andes.gob.ar/browse/MONIT-14
1. Buscador de conceptos snomed para consultar conceptos

MONITOREO: buscador de conceptos snomed

---

src/app/monitor-activaciones/interfaces/IPacienteApp.ts
src/app/monitor-activaciones/monitoreo-activaciones.component.html
src/app/monitor-activaciones/monitoreo-activaciones.component.ts
src/app/monitor-activaciones/services/pacienteApp.service.ts

https://proyectos.andes.gob.ar/browse/MONIT-23
https://proyectos.andes.gob.ar/browse/MONIT-24
1. Poder ver en activaciones el teléfono y el email del paciente seleccionado
2. Poder editar en activaciones el teléfono y el email del paciente seleccionado

MONITOREO: poder ver/editar el telefono y correo de pacienteApp en activaciones

---

src/app/cda/services/cda.service.ts

Cambia la ruta que realiza la generación de los CDA de un paciente
1. 
2. 
3.

fix(regenerarCda): actualiza la ruta

---

src/app/queries/componentes/query-execute.component.ts

Cambia xlsx por csv para la descarga de queries

bi-queries: Cambia xlsx por csv

---

src/app/conceptos-turneables/components/conceptos-turneables.component.ts

Ajusta los parámetros de búsqueda de conceptos turneables.

feat(conceptos-turneables): search by term

---

src/app/registro-novedades/components/novedades.component.html
src/app/registro-novedades/components/novedades.component.ts

https://proyectos.andes.gob.ar/browse/MISC-68
https://proyectos.andes.gob.ar/browse/MISC-70
1. Se permite la carga de una novedad sin módulo asociado
2. En el listado de novedades, se agregan los subtitulos a la columna de módulos
3. Se arregla el error de validación que se veía en algunos casos al cargar una nueva novedad

NOVEDADES: permitir la carga de novedades sin módulo

---

src/app/app.component.ts
src/app/queries/componentes/query-execute.component.html
src/app/queries/componentes/query-execute.component.ts

Agregar parametro tipo string para bi-queries
1. Agregar parametro tipo string para bi-queries
2. Cambia el envío de parámetro tipo fecha para envía horario cargado desde formulario
3.

feat(bi-queries): agrega parametro tipo string

---

package-lock.json
package.json
src/app/app.module.ts
src/app/modulos/components/modulos.component.css
src/app/modulos/components/modulos.component.html
src/app/modulos/components/modulos.component.ts
src/app/modulos/interfaces/IModulo.interface.ts
src/app/modulos/modulos.module.ts

Actualizar el ABM de módulos para la Epic de refactor visual punto inicio Andes
1. Se adaptó el formulario de AMB de módulos para soportar submódulos
2. Se usaron formularios reactivos
3. **Importante** hace falta correr script

feature(modulos): actualización punto inicio Andes

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/fuentes-autenticas/components/estado-fa.component.ts
src/app/fuentes-autenticas/components/estado-fa.html
src/app/fuentes-autenticas/services/fuentes-autenticas.service.ts

https://proyectos.andes.gob.ar/browse/MONIT-37
1. Nueva pantalla y servicio para verificar el estado de renaper y sisa

Pantalla para verificar estado de conexion en FA

---

src/app/cda/components/paciente/paciente-buscar.component.ts
src/app/cda/services/paciente.service.ts
src/app/monitor-activaciones/monitoreo-activaciones.component.html
src/app/monitor-activaciones/monitoreo-activaciones.component.ts

https://proyectos.andes.gob.ar/browse/MPI-325
1. Actualiza ruta de servicio de pacientes
2. Fix en aviso de buscador de pacientes que se inicializaba como búsqueda sin resultados

Activaciones - Actualiza servicio de pacientes a core-v2

---

src/app/monitor-activaciones/monitoreo-activaciones.component.html
src/app/monitor-activaciones/monitoreo-activaciones.component.ts

https://proyectos.andes.gob.ar/browse/MONIT-41
1. Se agrego la funcionalidad de poder buscar un usuario por el email.

feat(MONIT-41): buscar usuarios por email

---

src/app/cda/components/cda/cda-listado.component.ts
src/app/cda/components/cda/cda-listado.html
src/app/cda/components/regenerar-registros.component.ts

https://proyectos.andes.gob.ar/browse/MONIT-42

MONIT - Fix: Visualizar cdas de laboratorio

---

src/app/queries/componentes/query-execute.component.html
src/app/queries/componentes/query-execute.component.ts
src/app/services/organizacion.service.ts

Se agrega select para unidad organizativa
https://proyectos.andes.gob.ar/browse/IN-346
1. 
2. 
3. 
Query BD:
```
{
"_id" : ObjectId("61a53b87c9676ab6c9328a2f"),
"nombre" : "listado-movimientos-internacion",
"coleccion" : "internacionCamaEstados",
"descripcion" : "Listado de cantidad de movimientos de internación registrados y cantidad de internaciones",
"query" : [ 
{
"!match" : {
"start" : {
"!gte" : "#desde"
},
"end" : {
"!lte" : "#hasta"
},
"ambito" : "internacion",
"idOrganizacion" : "#organizacion",
"capa" : "#capa",
"estados.unidadOrganizativa.id" : "#unidadOrganizativa"
}
}, 
{
"!unwind" : "$estados"
}, 
{
"!match" : {
"estados.deletedAt" : {
"!exists" : false
},
"estados.unidadOrganizativa.id" : "#unidadOrganizativa",
"!or" : [ 
{
"estados.idInternacion" : {
"!ne" : null
}
}, 
{ …
```

Query: se agrega select por Unidad Organizativa

---

src/app/queries/componentes/query-execute.component.ts

https://proyectos.andes.gob.ar/browse/CORE-101

feat(bi-query): campo key configurable

---

src/app/conceptos-turneables/components/conceptos-turneables.component.html
src/app/conceptos-turneables/components/detalle-concepto-turneable.component.html
src/app/conceptos-turneables/components/detalle-concepto-turneable.component.ts

https://proyectos.andes.gob.ar/browse/MONIT-48
Se quitó el botón de eliminar concepto turneable. Se deja intacta la implementación del metodo onEliminarConceptoTurneable en conceptos-turneables.component para fix futuro del botón.

MONIT - Quitar boton de eliminacion de concepto turneable

---

src/app/rupers/components/atomo-create-update/atomo-create-update.component.html
src/app/rupers/components/atomo-create-update/atomo-create-update.component.ts
src/app/rupers/components/molecula-create-update/molecula-create-update.component.html
src/app/rupers/components/molecula-create-update/molecula-create-update.component.ts
src/app/rupers/components/prestacion-create-update/prestacion-create-update.component.html
src/app/rupers/components/prestacion-create-update/prestacion-create-update.component.ts
src/app/rupers/components/seccion-create-update/seccion-create-update.component.html
src/app/rupers/components/seccion-create-update/seccion-create-update.component.ts

Se agregan controles sobre botón guardar en la carga y actualización de los elementos RUP.
1. Se agregan controles sobre botón guardar.
2. Se agrega botón volver.
3.

fix (RUP): Se agregar controles sobre botones guardar

---

src/app/queries/componentes/query-execute.component.html

https://proyectos.andes.gob.ar/browse/BI-121
1. Se agrego la opcion "select-static" para que se pudiera visualizar un select con las opciones que corresponde. Tambien se hizo un refactor sobre la pantalla principal de bi-queries

BI - refactorizacion de la pantalla principal de bi-queries

---

src/app/rupers/components/atomo-create-update/atomo-create-update.component.html
src/app/rupers/components/atomo-create-update/atomo-create-update.component.ts
src/app/rupers/components/molecula-create-update/molecula-create-update.component.ts

Agrega soporte para CheckListComponent

feat(rupers): agrega checklist atomo

---

src/app/rupers/components/prestacion-create-update/prestacion-create-update.component.ts

https://proyectos.andes.gob.ar/browse/MONIT-55
1. Se corrigió error al agregar una prestación creada en monitoreo. Esto en RUP.

MONITOREO - Revisar alta de elemento RUP

---

src/app/app.module.ts
src/app/services/token-expired.interceptor.ts

https://proyectos.andes.gob.ar/browse/MONIT-50
1. Se implementa servicio interceptor de request http para chequear si hubo error de autorización tras vencimiento de token. En caso de haber error, se redirige al usuario a la pantalla de login.

MONIT - Agrega control para cierre de sesión al vencer token

---

src/app/rupers/components/atomo-create-update/atomo-create-update.component.html
src/app/rupers/components/atomo-create-update/atomo-create-update.component.ts

https://proyectos.andes.gob.ar/browse/MONIT-54
1. Al crear un átomo y seleccionar  Select Estático en Tipo Atomo, se agrega la posibilidad de agregar los ítems. Y también de eliminar el ítem.
2. Para el caso anterior. Al querer guardar el nuevo átomo. Solo se permite si al menos tiene cargado un item.
3. Para agregar un nuevo item, los campos Id y Label son obligatorios. No permite guardar espacios en blanco.
4. El botón Agregar Item despliega los campos Id y Label.
5. El botón + es para agregar el ítem.

MONITOREO - Elementos Rups: Select estático 

---

src/app/conceptos-turneables/Interfaces/IConceptoTurneable.ts
src/app/conceptos-turneables/components/conceptos-turneables.component.ts
src/app/conceptos-turneables/components/detalle-concepto-turneable.component.html
src/app/conceptos-turneables/components/detalle-concepto-turneable.component.ts
src/app/conceptos-turneables/components/nuevo-concepto-turneable.component.html
src/app/conceptos-turneables/components/nuevo-concepto-turneable.component.ts

https://proyectos.andes.gob.ar/browse/MONIT-58
1. Se agrega un nuevo switch para habilitar o deshabilitar el concepto para agenda dinámica.
https://github.com/andes/andes-test-integracion/pull/490

MONITOREO - Concepto Turneable: check  agenda dinamica

---

src/app/rupers/components/atomo-create-update/atomo-create-update.component.html
src/app/rupers/components/elementos-rup-listado/elementos-rup-listado.component.html
src/app/rupers/components/elementos-rup-listado/elementos-rup-listado.service.ts

https://proyectos.andes.gob.ar/browse/MONIT-57
1. En el listado de elementos rup ahora se visualizan todos los elementos activos y no sólo los que fueron creados desde esta pantalla.
2. Se corrigen detalles de visualización en la alineación del listado.

MONIT - Visualización listado de elementos rup

---

src/app/cda/components/paciente/paciente-listado.html
src/app/cda/components/regenerar-registros.component.ts
src/app/cda/components/regenerar-registros.html

https://proyectos.andes.gob.ar/browse/MONIT-59
1. Se muestra un plex-badge 'Inactivo' en el listado de pacientes si está inactivo.
2. Cuando esta inactivo, se ocultan los botones de registrar vacunas, regenerar y refrescar.

MONIT - Regenerar registros: Identificar paciente inactivo
